
CONST_TIMED_ROTATING_FILE_HANDLER = 'TimedRotatingFileHandler'
CONST_SOCKET_HANDLER = 'SocketHandler'
CONST_FILE_HANDLER = 'FileHandler'
CONST_ROTATING_FILE_HANDLER = 'RotatingFileHandler'
CONST_STREAM_HANDLER = 'StreamHandler'
CONST_NULL_HANDLER = 'NullHandler'
CONST_WATCHED_FILE_HANDLER = 'WatchedFileHandler'
CONST_DATAGRAM_HANDLER = 'DatagramHandler'
CONST_SYSLOG_HANDLER = 'SysLogHandler'
CONST_NT_EVENT_LOG_HANDLER = 'NTEventLogHandler'
CONST_SMTP_HANDLER = 'SMTPHandler'
CONST_MEMORY_HANDLER = 'MemoryHandler'
CONST_HTTP_HANDLER = 'HTTPHandler'


# Default Constants for SOKCET HANDLER
CONST_DEFAULT_HOST_IP = '54.67.35.135'
CONST_DEFAULT_PORT = 10020